mdtest: fix -i option
Check following regression:

./ior.git/src/mdtest -d a -i 3
ERROR: Unknown option type i
-- started at 09/05/2018 11:42:41 --

Signed-off-by: Wang Shilong <wshilong@ddn.com>